repositoryUrl: https://arche.acdh.oeaw.ac.at/api
auth:
  user: foo
  password: bar
classes:
  https://vocabs.acdh.oeaw.ac.at/schema#Person:
    - match: ^https://d-nb.info/gnd
      resolve: "%id%/about/lds.ttl"
      format: text/turtle
      mapping:
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
          type: id
          path:
            - http://www.w3.org/2002/07/owl#sameAs
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
          type: literal
          lang: und
          maxPerLang: 1
          path:
            - https://d-nb.info/standards/elementset/gnd#preferredNameForThePerson
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasFirstName
          type: literal
          lang: und
          maxPerLang: 1
          path:
            - https://d-nb.info/standards/elementset/gnd#preferredNameEntityForThePerson
            - https://d-nb.info/standards/elementset/gnd#forename
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLastName
          type: literal
          lang: und
          maxPerLang: 1
          path:
            - https://d-nb.info/standards/elementset/gnd#preferredNameEntityForThePerson
            - https://d-nb.info/standards/elementset/gnd#surname
  https://vocabs.acdh.oeaw.ac.at/schema#Organisation:
    - match: ^https://d-nb.info/gnd
      resolve: "%id%/about/lds.ttl"
      format: text/turtle
      mapping:
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
          type: id
          path:
            - http://www.w3.org/2002/07/owl#sameAs
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
          type: literal
          lang: und
          maxPerLang: 1
          path:
            - https://d-nb.info/standards/elementset/gnd#preferredNameForTheCorporateBody
  https://vocabs.acdh.oeaw.ac.at/schema#Place:
    - match: ^https://sws.geonames.org/
      resolve: "%id%/about.rdf"
      format: application/rdf+xml
      mapping:
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
          type: literal
          lang: und
          maxPerLang: 1
          path:
            - http://www.geonames.org/ontology#name
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
          type: literal
          maxPerLang: 1
          langRequired: true
          path:
            - http://www.geonames.org/ontology#officialName
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
          type: literal
          maxPerLang: 1
          langRequired: true
          path:
            - http://www.geonames.org/ontology#alternateName
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLatitude
          type: literal
          maxPerLang: 1
          path:
            - http://www.w3.org/2003/01/geo/wgs84_pos#lat
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLongitude
          type: literal
          maxPerLang: 1
          path:
            - http://www.w3.org/2003/01/geo/wgs84_pos#long

