# ARCHE repository base URL
repositoryUrl: https://arche-dev.acdh-dev.oeaw.ac.at/api
# ARCHE credentials.
# Required only if you update repository resources (run in the "update" mode)
auth:
  user: foo
  password: bar
namespaces:
  acdh: https://vocabs.acdh.oeaw.ac.at/schema#
  acdhi: https://id.acdh.oeaw.ac.at/
# defines conditions triggering processing of a given resource
namedEntities:
  # resource class
  https://vocabs.acdh.oeaw.ac.at/schema#Person:
  # missing properties - miss of any triggers processing
  - https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
  https://vocabs.acdh.oeaw.ac.at/schema#Place:
  - https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
  - https://vocabs.acdh.oeaw.ac.at/schema#hasLatitude
  - https://vocabs.acdh.oeaw.ac.at/schema#hasLongitude
  https://vocabs.acdh.oeaw.ac.at/schema#Organisation:
  - https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
# just a yaml syntax for reusing config part
sharedMappings:
  wikidataPerson: &wikidataPerson
  - property: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
    action: if missing
    value: https://vocabs.acdh.oeaw.ac.at/schema#Person
    type: resource
  # GND
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    action: add
    type: id
    path:
    - http://www.wikidata.org/prop/direct-normalized/P227
  # VIAF
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    action: add
    type: id
    path:
    - http://www.wikidata.org/prop/direct-normalized/P214
  # ORCID
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    action: add
    type: id
    path:
    - http://www.wikidata.org/prop/direct-normalized/P496
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    action: if missing
    type: literal
    langProcess: overwrite
    langValue: und
    preferredLangs:
      - en
      - de    
    path:
    - http://www.w3.org/2000/01/rdf-schema#label
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    action: if missing
    type: literal
    langProcess: overwrite
    langValue: und
    preferredLangs:
      - en
      - de    
    path:
    - http://www.w3.org/2004/02/skos/core#prefLabel
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    action: if missing
    type: literal
    langProcess: overwrite
    langValue: und
    preferredLangs:
      - en
      - de    
    path:
    - http://schema.org/name
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasFirstName
    action: if missing
    type: literal
    langProcess: overwrite
    langValue: und
    maxPerLang: 1
    path:
    - http://www.wikidata.org/prop/direct/P735
    - http://www.w3.org/2000/01/rdf-schema#label
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLastName
    action: if missing
    type: literal
    langProcess: overwrite
    langValue: und
    maxPerLang: 1
    path:
    - http://www.wikidata.org/prop/direct/P734
    - http://www.w3.org/2000/01/rdf-schema#label
  wikidataPlace: &wikidataPlace
  - property: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
    action: if missing
    value: https://vocabs.acdh.oeaw.ac.at/schema#Place
    type: resource
  # GND
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    action: add
    type: id
    path:
    - http://www.wikidata.org/prop/direct-normalized/P227
  # VIAF
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    action: add
    type: id
    path:
    - http://www.wikidata.org/prop/direct-normalized/P214
  # geonames
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    action: add
    type: id
    path:
    - http://www.wikidata.org/prop/direct-normalized/P1566
  # GETTY
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    action: add
    type: id
    path:
    - http://www.wikidata.org/prop/direct-normalized/P1667
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    action: if missing
    type: literal
    langProcess: assure
    langValue: und
    preferredLangs:
      - en
      - de    
    path:
    - http://www.w3.org/2000/01/rdf-schema#label
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    action: if missing
    type: literal
    langProcess: assure
    langValue: und
    preferredLangs:
      - en
      - de    
    path:
    - http://www.w3.org/2004/02/skos/core#prefLabel
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    action: if missing
    type: literal
    langProcess: assure
    langValue: und
    preferredLangs:
      - en
      - de    
    path:
    - http://schema.org/name
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLatitude
    action: if missing
    type: literal
    maxPerLang: 1
    match: ^Point[(][0-9.]+ ([0-9.]+)[)]$
    replace: \1
    datatype: http://www.w3.org/2001/XMLSchema#float
    path:
    - http://www.wikidata.org/prop/direct/P625
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLongitude
    action: if missing
    type: literal
    maxPerLang: 1
    match: ^Point[(]([0-9.]+) [0-9.]+[)]$
    replace: \1
    datatype: http://www.w3.org/2001/XMLSchema#float
    path:
    - http://www.wikidata.org/prop/direct/P625
  gettyPlace: &gettyPlace
  - property: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
    action: if missing
    value: https://vocabs.acdh.oeaw.ac.at/schema#Place
    type: resource
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    action: if missing
    type: literal
    langProcess: assure
    langValue: und
    maxPerLang: 1
    preferredLangs:
      - en
      - de
    path:
    - http://www.w3.org/2004/02/skos/core#prefLabel
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasAlternativeTitle
    action: add
    type: literal
    langProcess: assure
    langValue: und
    preferredLangs:
      - en
      - de
    path:
    - http://www.w3.org/2004/02/skos/core#altLabel
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLatitude
    action: if missing
    type: literal
    maxPerLang: 1
    datatype: http://www.w3.org/2001/XMLSchema#float
    path:
    - http://xmlns.com/foaf/0.1/focus
    - http://www.w3.org/2003/01/geo/wgs84_pos#lat
  - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLongitude
    action: if missing
    type: literal
    maxPerLang: 1
    datatype: http://www.w3.org/2001/XMLSchema#float
    path:
    - http://xmlns.com/foaf/0.1/focus
    - http://www.w3.org/2003/01/geo/wgs84_pos#long
referenceSources:
  # identifier of the external authority file matching the UriNormalizer rule's
  # `name` property, see e.g. https://github.com/acdh-oeaw/arche-assets/blob/master/AcdhArcheAssets/uriNormRules.json
  gnd:
    # class reported by the external authority file
    https://d-nb.info/standards/elementset/gnd#DifferentiatedPerson:
      # ARCHE schema property
    - property: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
      action: if missing
      # set a fixed value
      value: https://vocabs.acdh.oeaw.ac.at/schema#Person
      type: resource
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
      # How to merge extracted values with values from other databases
      # - add - just take union of all values
      # - replace - replace already harvested values with values extracted from this database
      #             (as databases are processed in the order given in the config file
      #              this can be still influenced by below-defined database mappings)
      # - if missing - add values only if a given property has no value yet
      action: add
      # ARCHE schema property type: id, literal or resource
      type: id
      # Path of RDF properties leading to the given property in the RDF metadata
      # provided by the external reference source.
      # In the simple case (like here) just an equivalent property in the external reference source.
      path:
      - http://www.w3.org/2002/07/owl#sameAs
      # (optional) Only values matching given regexp will be included.
      # Can be used e.g. to allow only identifiers in allowed namespaces (like here).
      # (if "match" is provided, both conditions must be fulfilled)
      match: viaf.org|wikidata.org|d-nb.info|orcid.org
      # (optional) Only values which don't match given regexp will be included.
      # Can be used e.g. to skip identifiers in namespaces we don't trust (like here).
      # (if "match" is provided, both conditions must be fulfilled)
      skip: isni.org|id.loc.gov.pl
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
      action: if missing
      type: literal
      # An optional list of preffered languages
      # First, if it is provided, then only values in these langs are kept.
      # Second, if `maxPerLang` is used in combination with `langProcess` other than `pass`,
      # value are sorted first according to their lang position on this list, e.g.
      # with `maxPerLang: 1, langProcess: override, langValue: und, preferrredLangs: ['en', 'de']` 
      # `and inputs values of `foo@de`, `bar@fr` and `baz@en`, the final value will be `baz@und`
      # (`bar@fr` will be dropped because its lang is not on the `preferrredLangs` list and
      # the value in `en` will be prefered over `de` as `en` is first on the `preferrredLangs` list)
      preferredLangs: []
      # One of:
      # - overwrite - forcefully set lang of all values to the `langValue` config property value
      # - assure [default] - if lang is missing, set it to the `langValue` config property value
      #                      (note that if `langValue` is missing or empty, it's equivalent to "pass")
      # - remove - drop all lang tags
      # - pass - just pass what's in the data
      # It's worth nothing language tag is processed only when `type` config property equals "literal"
      langProcess: overwrite
      langValue: und
      # Maximum number of values per lang tag value
      # The first value(s) is(are) kept with sorting being described in the `preferredLang` property
      # description. In case of equal order according to the lang, lexically smaller value(s) is(are)
      # kept.
      maxPerLang: 1
      path:
      - https://d-nb.info/standards/elementset/gnd#preferredNameForThePerson
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasFirstName
      action: if missing
      type: literal
      langProcess: overwrite
      langValue: und
      maxPerLang: 1
      path:
      - https://d-nb.info/standards/elementset/gnd#preferredNameEntityForThePerson
      - https://d-nb.info/standards/elementset/gnd#forename
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLastName
      action: if missing
      type: literal
      langProcess: overwrite
      langValue: und
      maxPerLang: 1
      path:
      - https://d-nb.info/standards/elementset/gnd#preferredNameEntityForThePerson
      - https://d-nb.info/standards/elementset/gnd#surname
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasUrl
      action: add
      type: literal
      path:
      - https://d-nb.info/standards/elementset/gnd#homepage
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasDescription
      action: replace
      type: literal
      path:
      - https://d-nb.info/standards/elementset/gnd#biographicalOrHistoricalInformation
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasAlternativeTitle
      action: add
      type: literal
      langProcess: assure
      langValue: und
      maxPerLang: 3
      path:
      - https://d-nb.info/standards/elementset/gnd#variantNameForThePerson
    https://d-nb.info/standards/elementset/gnd#CorporateBody:
    - property: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
      action: if missing
      value: https://vocabs.acdh.oeaw.ac.at/schema#Organisation
      type: resource
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
      action: add
      type: id
      path:
      - http://www.w3.org/2002/07/owl#sameAs
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
      action: if missing
      type: literal
      langProcess: overwrite
      langValue: und
      maxPerLang: 1
      path:
      - https://d-nb.info/standards/elementset/gnd#preferredNameForTheCorporateBody
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasAddress
      action: replace
      type: literal
      path:
      - https://d-nb.info/standards/elementset/gnd#placeOfBusiness
      - https://d-nb.info/standards/elementset/gnd#preferredNameForThePlaceOrGeographicName
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasUrl
      action: add
      type: literal
      path:
      - https://d-nb.info/standards/elementset/gnd#homepage
  viaf:
    http://schema.org/Person:
    - property: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
      action: if missing
      value: https://vocabs.acdh.oeaw.ac.at/schema#Person
      type: resource
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
      action: add
      type: id
      path:
      - http://schema.org/sameAs
      # orcid in viaf seems strange - skipping
      match: viaf.org|wikidata.org|d-nb.info
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
      action: if missing
      type: literal
      preferredLangs:
      - en-GB
      - en-US
      - de-DE
      langProcess: overwrite
      langValue: und
      maxPerLang: 1
      path:
      - http://www.w3.org/2004/02/skos/core#prefLabel
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasFirstName
      action: if missing
      type: literal
      langProcess: assure
      langValue: und
      maxPerLang: 1
      path:
      - http://schema.org/givenName
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLastName
      action: if missing
      type: literal
      langProcess: assure
      langValue: und
      maxPerLang: 1
      path:
      - http://schema.org/familyName
  orcid:
    http://xmlns.com/foaf/0.1/Person:
    - property: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
      action: if missing
      value: https://vocabs.acdh.oeaw.ac.at/schema#Person
      type: resource
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
      action: if missing
      type: literal
      langProcess: overwrite
      langValue: und
      maxPerLang: 1
      path:
      - http://www.w3.org/2000/01/rdf-schema#label
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasFirstName
      action: if missing
      type: literal
      langProcess: assure
      langValue: und
      maxPerLang: 1
      path:
      - http://xmlns.com/foaf/0.1/givenName
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLastName
      action: if missing
      type: literal
      langProcess: assure
      langValue: und
      maxPerLang: 1
      path:
      - http://xmlns.com/foaf/0.1/familyName
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasUrl
      action: add
      type: literal
      path:
      - http://xmlns.com/foaf/0.1/page
  geonames:
    http://www.geonames.org/ontology#Feature:
    - property: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
      action: if missing
      value: https://vocabs.acdh.oeaw.ac.at/schema#Place
      type: resource
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
      action: if missing
      type: literal
      langProcess: overwrite
      langValue: und
      maxPerLang: 1
      path:
      - http://www.geonames.org/ontology#name
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
      action: if missing
      type: literal
      maxPerLang: 1
      langProcess: assure
      langValue: und
      path:
      - http://www.geonames.org/ontology#officialName
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasAlternativeTitle
      action: add
      type: literal
      maxPerLang: 1
      langProcess: assure
      langValue: und
      path:
      - http://www.geonames.org/ontology#alternateName
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLatitude
      action: if missing
      type: literal
      maxPerLang: 1
      path:
      - http://www.w3.org/2003/01/geo/wgs84_pos#lat
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLongitude
      action: if missing
      type: literal
      maxPerLang: 1
      path:
      - http://www.w3.org/2003/01/geo/wgs84_pos#long
  getty:
    http://vocab.getty.edu/ontology#AdminPlaceConcept: *gettyPlace
    http://vocab.getty.edu/ontology#PhysPlaceConcept: *gettyPlace
    http://vocab.getty.edu/ontology#PhysAdminPlaceConcept: *gettyPlace
  wikidata:
    http://www.wikidata.org/entity/Q200250: *wikidataPlace
    http://www.wikidata.org/entity/Q200250: *wikidataPlace
    http://www.wikidata.org/entity/Q515: *wikidataPlace
    http://www.wikidata.org/entity/Q7930989: *wikidataPlace
    http://www.wikidata.org/entity/Q124250988: *wikidataPlace
    http://www.wikidata.org/entity/Q486972: *wikidataPlace
    http://www.wikidata.org/entity/Q123964505: *wikidataPlace
    http://www.wikidata.org/entity/Q839954: *wikidataPlace
    http://www.wikidata.org/entity/Q2221906: *wikidataPlace
    http://www.wikidata.org/entity/Q17334923: *wikidataPlace
    http://www.wikidata.org/entity/Q27096213: *wikidataPlace
    http://www.wikidata.org/entity/Q5: *wikidataPerson
  acdh-iso6393:
    http://www.w3.org/2004/02/skos/core#Concept:
    - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
      action: if missing
      type: literal
      langProcess: assure
      langValue: und
      maxPerLang: 1
      path:
      - http://www.w3.org/2004/02/skos/core#prefLabel
