# ARCHE repository base URL
repositoryUrl: https://arche.acdh.oeaw.ac.at/api
# ARCHE credentials.
# Required only if you update repository resources (run in the "update" mode)
auth:
  user: foo
  password: bar
# Which resource classes to process and how to do it
classes:
  # Class URI as the key
  # Value is an array of external reference source definitions for a given class
  https://vocabs.acdh.oeaw.ac.at/schema#Person:
      # Only resources with identifiers matching the "match" regexp are resolved
      # against the given external reference source
    - match: ^https://d-nb.info/gnd
      # External reference source URL template
      # (%id% is substituted with the ARCHE resource identifier witch matched the "match" regexp)
      resolve: "%id%/about/lds.ttl"
      # (optional) The expected RDF format delivered by the external reference source
      format: text/turtle
      # Mapping of the RDF provided by the external reference source to the ARCHE schema
      mapping:
          # ARCHE schema property
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
          # ARCHE schema property type: id, literal or resource
          type: id
          # Path of RDF properties leading to the given property in the RDF metadata
          # provided by the external reference source.
          # In the simple case (like here) just an equivalent property in the external reference source.
          path:
            - http://www.w3.org/2002/07/owl#sameAs
          # (optional) Only values matching given regexp will be included.
          # Can be used e.g. to allow only identifiers in allowed namespaces (like here).
          # (if "match" is provided, both conditions must be fulfilled)
          match: viaf.org|wikidata.org|d-nb.info
          # (optional) Only values which don't match given regexp will be included.
          # Can be used e.g. to skip identifiers in namespaces we don't trust (like here).
          # (if "match" is provided, both conditions must be fulfilled)
          skip: isni.org|id.loc.gov.pl
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
          type: literal
          forceLang: und
          maxPerLang: 1
          path:
            - https://d-nb.info/standards/elementset/gnd#preferredNameForThePerson
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasFirstName
          type: literal
          forceLang: und
          maxPerLang: 1
          path:
            - https://d-nb.info/standards/elementset/gnd#preferredNameEntityForThePerson
            - https://d-nb.info/standards/elementset/gnd#forename
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLastName
          type: literal
          forceLang: und
          maxPerLang: 1
          path:
            - https://d-nb.info/standards/elementset/gnd#preferredNameEntityForThePerson
            - https://d-nb.info/standards/elementset/gnd#surname
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasUrl
          type: literal
          path:
            - https://d-nb.info/standards/elementset/gnd#homepage
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasDescription
          type: literal
          path:
            - https://d-nb.info/standards/elementset/gnd#biographicalOrHistoricalInformation
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasAlternativeTitle
          type: literal
          langRequired: true
          defaultLang: und
          path:
            - https://d-nb.info/standards/elementset/gnd#variantNameForThePerson
    - match: ^https://orcid.org
      resolve: "%id%"
      format: text/turtle
      mapping:
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
          type: literal
          forceLang: und
          maxPerLang: 1
          path:
            - http://www.w3.org/2000/01/rdf-schema#label
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasFirstName
          type: literal
          langRequired: true
          defaultLang: und
          maxPerLang: 1
          path:
            - http://xmlns.com/foaf/0.1/givenName
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLastName
          type: literal
          langRequired: true
          defaultLang: und
          maxPerLang: 1
          path:
            - http://xmlns.com/foaf/0.1/familyName
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasUrl
          type: literal
          path:
            - http://xmlns.com/foaf/0.1/page
https://vocabs.acdh.oeaw.ac.at/schema#Organisation:
    - match: ^https://d-nb.info/gnd
      resolve: "%id%/about/lds.ttl"
      format: text/turtle
      mapping:
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
          type: id
          path:
            - http://www.w3.org/2002/07/owl#sameAs
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
          type: literal
          forceLang: und
          maxPerLang: 1
          path:
            - https://d-nb.info/standards/elementset/gnd#preferredNameForTheCorporateBody
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasAlternativeTitle
          type: literal
          langRequired: true
          defaultLang: und
          path:
            - https://d-nb.info/standards/elementset/gnd#variantNameForTheCorporateBody
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasAddress
          type: literal
          path:
            - https://d-nb.info/standards/elementset/gnd#placeOfBusiness
            - https://d-nb.info/standards/elementset/gnd#preferredNameForThePlaceOrGeographicName
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasCountry
          type: literal
          path:
            - https://d-nb.info/standards/elementset/gnd#geographicAreaCode
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasUrl
          type: literal
          path:
            - https://d-nb.info/standards/elementset/gnd#homepage
https://vocabs.acdh.oeaw.ac.at/schema#Place:
    - match: ^https://sws.geonames.org/
      resolve: "%id%/about.rdf"
      format: application/rdf+xml
      mapping:
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
          type: literal
          forceLang: und
          maxPerLang: 1
          path:
            - http://www.geonames.org/ontology#name
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
          type: literal
          maxPerLang: 1
          langRequired: true
          defaultLang: und
          path:
            - http://www.geonames.org/ontology#officialName
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasAlternativeTitle
          type: literal
          maxPerLang: 1
          langRequired: true
          defaultLang: und
          path:
            - http://www.geonames.org/ontology#alternateName
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLatitude
          type: literal
          maxPerLang: 1
          path:
            - http://www.w3.org/2003/01/geo/wgs84_pos#lat
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLongitude
          type: literal
          maxPerLang: 1
          path:
            - http://www.w3.org/2003/01/geo/wgs84_pos#long
    - match: ^http://vocab.getty.edu
      resolve: "%id%"
      format: text/turtle
      mapping:
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
          type: literal
          langRequired: true
          defaultLang: und
          maxPerLang: 1
          path:
            - http://www.w3.org/2004/02/skos/core#prefLabel
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasAlternativeTitle
          type: literal
          langRequired: true
          defaultLang: und
          path:
            - http://www.w3.org/2004/02/skos/core#altLabel
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLatitude
          type: literal
          maxPerLang: 1
          path:
            - http://xmlns.com/foaf/0.1/focus
            - http://www.w3.org/2003/01/geo/wgs84_pos#lat
        - property: https://vocabs.acdh.oeaw.ac.at/schema#hasLongitude
          type: literal
          maxPerLang: 1
          path:
            - http://xmlns.com/foaf/0.1/focus
            - http://www.w3.org/2003/01/geo/wgs84_pos#long

